### ISSUE TITLE
Allow switching from "p-queue" to a queue with persistence mechanism

### ISSUE THREAD

**Issue by IuriiD** [langchain-ai/langchainjs#1587]
[langchainjs](https://github.com/hwchase17/langchainjs) is [using](langchain/src/util/async_caller.ts) [p-queue](https://www.npmjs.com/package/p-queue) to address possible rate-limiting from LLM APIs. This means that if our app restarts, the queued requests will be lost.
- How valid is this concern? Has anyone faced issues with such in-memory queueing and app restarts?
- Are there any plans in the roadmap to support queues with persistent storage in langchainjs? If maybe not, are there any recommendations in this sense?
Thanks in advance!

**Comment by dziuban-iurii** [comment]
This question seems to be relevant to us. Just curious if anyone else is concerned about this aspect? Is there any info about using TS Langchain under high load?

**Comment by ishaan-jaff** [comment]
@IuriiD @dziuban-iurii I'm the maintainer of LiteLLM - we allow you to use persistent request queues **(and it's compatible with langchain js)**. Hope this is useful for your use case 

Here's a quick start on this:

docs: https://docs.litellm.ai/docs/routing#queuing-beta 

### Quick Start 

1. Add Redis credentials in a .env file

```python
REDIS_HOST="my-redis-endpoint"
REDIS_PORT="my-redis-port"
REDIS_PASSWORD="my-redis-password" # [OPTIONAL] if self-hosted
REDIS_USERNAME="default" # [OPTIONAL] if self-hosted
```

2. Start litellm server with your model config

```bash
$ litellm --config /path/to/config.yaml --use_queue
```

Here's an example config for `gpt-3.5-turbo`

**config.yaml** (This will load balance between OpenAI + Azure endpoints)
```yaml
model_list: 
  - model_name: gpt-3.5-turbo
    litellm_params: 
      model: gpt-3.5-turbo
      api_key: 
  - model_name: gpt-3.5-turbo
    litellm_params: 
      model: azure/chatgpt-v-2 # actual model name
      api_key: 
      api_version: 2023-07-01-preview
      api_base: https://openai-gpt-4-test-v-1.openai.azure.com/
```

3. Test (in another window) → sends 100 simultaneous requests to the queue 

```bash
$ litellm --test_async --num_requests 100
```


### Available Endpoints
- `/queue/request` - Queues a /chat/completions request. Returns a job id. 
- `/queue/response/{id}` - Returns the status of a job. If completed, returns the response as well. Potential status's are: `queued` and `finished`.
