### ISSUE TITLE
What mean of "Not Found"

### ISSUE THREAD

**Issue by meithon** [langchain-ai/langchainjs#4096]
I executed this code.
```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import weaviate from "weaviate-ts-client";
import { WeaviateStore } from "@langchain/community/vectorstores/weaviate";
import { OpenAIEmbeddings } from "@langchain/openai";

export async function run() {
  // Something wrong with the weaviate-ts-client types, so we need to disable
  const client = weaviate.client({
    scheme: process.env.WEAVIATE_SCHEME || "http",
    host: process.env.WEAVIATE_HOST || "localhost:8080",
  });
  const docs = [{ pageContent: "see ya!", metadata: { foo: "bar" } }];

  WeaviateStore.fromDocuments(docs, new OpenAIEmbeddings(), {
    client,
    indexName: "Test",
  });
}

run();
```
Returned this error
```sh
150 |             if (errorMessages.length > 0) {
151 |                 throw new Error(errorMessages.join("\n"));
152 |             }
153 |         }
154 |         catch (e) {
155 |             throw Error(`Error adding vectors: ${e}`);
                        ^
error: Error adding vectors: Error: usage error (404): {"detail":"Not Found"}
      at /Users/mei/workspace/private/langchain-ts/node_modules/@langchain/community/dist/vectorstores/weaviate.js:155:19
```

What was not found for this?
And how can this be resolved?

**Comment by rneithon** [comment]
I use this docker-compose.yml
```yml
version: "3.4"
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: semitechnologies/weaviate:1.23.3
    env_file: .env
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QNA_INFERENCE_API: "http://qna-transformers:8080"
      NER_INFERENCE_API: "http://ner-transformers:8080"
      SPELLCHECK_INFERENCE_API: "http://text-spellcheck:8080"
      OPENAI_APIKEY: $OPENAI_API_KEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "text2vec-openai"
      ENABLE_MODULES: "text2vec-openai,qna-transformers,ner-transformers,text-spellcheck,ref2vec-centroid,generative-openai"
      CLUSTER_HOSTNAME: "node1"
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: "0"
  ner-transformers:
    image: semitechnologies/ner-transformers:dbmdz-bert-large-cased-finetuned-conll03-english
    environment:
      ENABLE_CUDA: "0"
  text-spellcheck:
    image: semitechnologies/text-spellcheck-model:pyspellchecker-en
volumes:
  weaviate_data:
```
